name: Status Checks

on:
  issues:
    types: [assigned, unassigned]

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.2.0
      - name: Status Initialization
        run: |
          Import-Module "${{ github.workspace }}/scripts/validation.psm1"
          $arguments = @{
            issueNumber = ${{ github.event.issue.number }}
            repository  = "${{ github.event.repository.full_name }}"
          }
          Update-IssueStatus @arguments
        shell: pwsh
